# fly.toml app configuration file generated for climbing-team-mysql on 2024-03-06T21:16:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'climbing-team-mysql'
primary_region = 'lhr'

[build]
  image = 'mysql:8'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[processes]
  app = """--datadir /data/mysql \
    --default-authentication-plugin mysql_native_password"""

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  MYSQL_DATABASE = "climbing"
  MYSQL_USER = "climbing"

