version: 1.0

deploy:
  # configuration part, which is taken at the FIRST deployment of each branch
  bootstrap:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - mkdir storage/logs
      - php artisan about
      - php artisan down
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan migrate --force -n
      - php artisan optimize:clear
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

  # configuration part, which is taken at ALL FURTHER deployments of this branch
  recurring:
    # folders that are not copied to IONOS webspace
    excludes:
      - tests
      - node_modules
      - DOCKER_ENV
      - docker_tag
      - output.log
      - storage
    # commands that are executed at the real webspace NOT at build servers BEFORE copying new files
    pre-deployment-remote-commands:
      - php artisan down
    # commands that are executed at the real webspace NOT at build servers AFTER copying new files
    post-deployment-remote-commands:
      - find $(pwd) -type f -not -path "$(pwd)/logs/*" -exec chmod 664 {} \;
      - find $(pwd) -type d -not -name "logs" -exec chmod 775 {} \;
      - chmod -R o+w storage bootstrap/cache
      - php artisan optimize:clear
      - php artisan migrate --force -n
      - php artisan storage:link
      - php artisan optimize
      - php artisan up

runtime:
 cron-jobs:
   # the deployment is located at $HOME/htdocs/ to execute a deployed script just prefix it accordingly
   - command: cd $HOME/htdocs/ && php artisan schedule:run >> /dev/null 2>&1
     schedule: "* * * * *" # every minute
