name: Deploy to Webspace

concurrency: deploy-production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://climbfoxcoverts.co.uk/
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          sparse-checkout: |
            /*
            !.devcontainer
            !.editorconfig
            !.env.*
            !.prettierrc
            !DOCKER_ENV
            !docker_tag
            !docker-compose.yml
            !node_modules
            !output.log
            !storage
            !tests

      - name: Setup PHP with composers
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, dom, fileinfo, mysql
          tools: composer:v2

      - name: Get composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader --no-dev

      - name: Generate dotenv file
        uses: iamsauravsharma/create-dotenv@v2.0.1
        with:
          input-prefix: DOTENV_
        env:
          DOTENV_DB_CONNECTION=mysql
          DOTENV_DB_HOST=${{ vars.DB_HOST }}
          DOTENV_DB_PORT=${{ vars.DB_PORT }}
          DOTENV_DB_DATABASE=${{ vars.DB_NAME }}
          DOTENV_DB_USERNAME="${{ vars.DB_USERNAME }}"
          DOTENV_DB_PASSWORD="${{ secrets.DB_PASSWORD }}"

          DOTENV_MAIL_MAILER=${{ vars.MAILER }}

          DOTENV_MAIL_HOST=${{ vars.MAIL_HOST }}
          DOTENV_MAIL_PORT=${{ vars.MAIL_PORT }}
          DOTENV_MAIL_USERNAME="${{ vars.MAIL_USERNAME }}"
          DOTENV_MAIL_PASSWORD="${{ secrets.MAIL_PASSWORD }}"
          DOTENV_MAIL_ENCRYPTION=${{ vars.MAIL_ENCRYPTION }}

          DOTENV_SENDGRID_API_KEY=${{ vars.SENDGRID_API_KEY }}

      - name: Build PHP assets
        run: php artisan key:generate --force -n

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v20.x
          cache: yarn

      - name: Build Node assets
        env:
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          yarn install --frozen-lockfile
          yarn build

      - name: Put the site in maintenance mode
        run: php artisan down --render=down.deploy --retry=60 --refresh=15

      - name: Upload files to server
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          port: ${{ vars.SSH_PORT }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
          local_path: './*'
          remote_path: ${{ vars.SSH_PATH }}
          sftpArgs: '-o ConnectTimeout=5'

      - name: Run deploy scripts
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          port: ${{ vars.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: "cd ${{ vars.SSH_PATH }} && ./.deploy/push.sh"