name: Test

on: push

jobs:
  test:
    name: Artisan Test
    runs-on: ubuntu-latest

    env:
      APP_ENV: testing
      DB_CONNECTION: mariadb
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_HOST: 127.0.0.1
      DB_PORT: 32574
      BROADCAST_DRIVER: log
      CACHE_DRIVER: database
      SESSION_DRIVER: database

    services:
      mariadb:
        image: mariadb:10.4
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_PASSWORD: "${{ env.DB_PASSWORD }}"
          MYSQL_DATABASE: "${{ env.DB_DATABASE }}"
        ports:
          - "32574:3306"
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2']

    steps:
      - uses: actions/checkout@v4
      - uses: php-actions/composer@v6
      - uses: actions/setup-node@v4
        with:
          node-version: v20.x
          cache: yarn

      - name: Build assets
        env:
          SITE_URL: https://climbfoxcoverts.co.uk/
        run: |
          yarn install --frozen-lockfile
          yarn build

      - uses: php-actions/phpunit@v3
        with:
          php_version: ${{ matrix.php-version }}
          php_extensions: mbstring dom fileinfo pdo-mysql
          args: --coverage-text

